// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdlJBWHSUhxVvtfCHx_40TR5yUgvdNScU',
    appId: '1:799490878546:web:71af3a735d6715bc81038b',
    messagingSenderId: '799490878546',
    projectId: 'chatter-box-5af67',
    authDomain: 'chatter-box-5af67.firebaseapp.com',
    storageBucket: 'chatter-box-5af67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHgIjcTV3U8rcEkwNpGrF8VfVmeqEc_7A',
    appId: '1:799490878546:android:6b1be2f17ab5944a81038b',
    messagingSenderId: '799490878546',
    projectId: 'chatter-box-5af67',
    storageBucket: 'chatter-box-5af67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5r6eVBrKJ-4gIC9T3rvt_buga7gOWA8U',
    appId: '1:799490878546:ios:913c77a832868fa981038b',
    messagingSenderId: '799490878546',
    projectId: 'chatter-box-5af67',
    storageBucket: 'chatter-box-5af67.firebasestorage.app',
    iosBundleId: 'com.example.chatterBox',
  );
}
